/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sat Jan 11 13:07:44 2020. */

#include "protocol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const float Config_Callibration_x_offset_default = 0;
const float Config_Callibration_y_offset_default = 0;
const float Config_Callibration_z_offset_default = 0;
const float Config_PidConfig_p_default = 1200;
const float Config_PidConfig_d_default = 0.65;
const float Config_PidConfig_i_default = 0.1;
const float Config_PidConfig_max_i_default = 3;
const float Config_BalancingConfig_balance_expo_default = 0.15;
const uint32_t Config_BalancingConfig_global_gyro_lpf_default = 2u;
const float Config_BalancingConfig_imu_beta_default = 0.02;
const int32_t Config_BalancingConfig_max_control_angle_default = 30;
const int32_t Config_BalancingConfig_max_rotation_rate_default = 360;
const int32_t Config_BalancingConfig_max_current_default = 25;
const float Config_BalancingConfig_rc_lpf_default = 0.007;
const int32_t Config_BalancingConfig_stop_balance_angle_default = 10;


const pb_field_t Config_fields[5] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, Config, callibration, callibration, &Config_Callibration_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, Config, balance_pid, callibration, &Config_PidConfig_fields),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, Config, yaw_pid, balance_pid, &Config_PidConfig_fields),
    PB_FIELD(  4, MESSAGE , REQUIRED, STATIC  , OTHER, Config, balance_settings, yaw_pid, &Config_BalancingConfig_fields),
    PB_LAST_FIELD
};

const pb_field_t Config_Callibration_fields[4] = {
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , FIRST, Config_Callibration, x_offset, x_offset, &Config_Callibration_x_offset_default),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, Config_Callibration, y_offset, x_offset, &Config_Callibration_y_offset_default),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, Config_Callibration, z_offset, y_offset, &Config_Callibration_z_offset_default),
    PB_LAST_FIELD
};

const pb_field_t Config_PidConfig_fields[5] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, Config_PidConfig, p, p, &Config_PidConfig_p_default),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Config_PidConfig, d, p, &Config_PidConfig_d_default),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, Config_PidConfig, i, d, &Config_PidConfig_i_default),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, Config_PidConfig, max_i, i, &Config_PidConfig_max_i_default),
    PB_LAST_FIELD
};

const pb_field_t Config_BalancingConfig_fields[9] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, Config_BalancingConfig, balance_expo, balance_expo, &Config_BalancingConfig_balance_expo_default),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Config_BalancingConfig, global_gyro_lpf, balance_expo, &Config_BalancingConfig_global_gyro_lpf_default),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, Config_BalancingConfig, imu_beta, global_gyro_lpf, &Config_BalancingConfig_imu_beta_default),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, Config_BalancingConfig, max_control_angle, imu_beta, &Config_BalancingConfig_max_control_angle_default),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, Config_BalancingConfig, max_rotation_rate, max_control_angle, &Config_BalancingConfig_max_rotation_rate_default),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, Config_BalancingConfig, max_current, max_rotation_rate, &Config_BalancingConfig_max_current_default),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, Config_BalancingConfig, rc_lpf, max_current, &Config_BalancingConfig_rc_lpf_default),
    PB_FIELD(  8, INT32   , OPTIONAL, STATIC  , OTHER, Config_BalancingConfig, stop_balance_angle, rc_lpf, &Config_BalancingConfig_stop_balance_angle_default),
    PB_LAST_FIELD
};

const pb_field_t Stats_fields[13] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, Stats, batt_voltage, batt_voltage, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Stats, batt_current, batt_voltage, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, Stats, motor_current, batt_current, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, Stats, speed, motor_current, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, Stats, distance_traveled, speed, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, Stats, drive_angle, distance_traveled, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, Stats, stear_angle, drive_angle, 0),
    PB_FIELD(  9, UINT32  , REQUIRED, STATIC  , OTHER, Stats, pad_pressure1, stear_angle, 0),
    PB_FIELD( 10, UINT32  , REQUIRED, STATIC  , OTHER, Stats, pad_pressure2, pad_pressure1, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, Stats, motor_duty, pad_pressure2, 0),
    PB_FIELD( 12, FLOAT   , REQUIRED, STATIC  , OTHER, Stats, esc_temp, motor_duty, 0),
    PB_FIELD( 13, FLOAT   , REQUIRED, STATIC  , OTHER, Stats, motor_temp, esc_temp, 0),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Config, callibration) < 65536 && pb_membersize(Config, balance_pid) < 65536 && pb_membersize(Config, yaw_pid) < 65536 && pb_membersize(Config, balance_settings) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Config_Config_Callibration_Config_PidConfig_Config_BalancingConfig_Stats)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Config, callibration) < 256 && pb_membersize(Config, balance_pid) < 256 && pb_membersize(Config, yaw_pid) < 256 && pb_membersize(Config, balance_settings) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Config_Config_Callibration_Config_PidConfig_Config_BalancingConfig_Stats)
#endif


/* @@protoc_insertion_point(eof) */
